### ISSUE TITLE
Some questions about the current project

### ISSUE THREAD

**Issue by GorEldeen** [cdpude/GodotBeautifier#3]
Hey CD!
I had some questions in my mind, Please don't mind if they were silly

1. Will it support godot 4 later?
2. Will it support using custom themes and wallpapers?

also want to ask if you have a way to contact (Discord, Instagram etc.)

other than that, Hope you have a nice day <3

**Comment by cdpude** [comment]
Nice to see you again!
1. Yes, it will support godot 4 later.
2. Yes, but I still have no idea how to do.

yes, I have. my discord account is cdpude#8720
hope you have a nice day too :kissing:

**Comment by GorEldeen** [comment]
Hey, it's been a while
i've came back to Godot 3 and i remembered this plugin, it's so amazing and gave me back good memories
Hope you're doing fine.

yours forever, GorEldeen

**Comment by cdpude** [comment]
Thanks for asking, hope you're doing fine too. <3
